### PR TITLE
Dependency fix when depending on worlds and systems

### LINKED ISSUE #96: Error when rendering BugReportForm if module has non-module dependencies
**Submitted By**: Wigsinator#2306
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** bug-reporter v1.2.1
 
**Description**:
How to Reproduce:
1) Create a module with a dependency on a system or world
2) Add Bug Reporter functionality
3) Attempt to report a bug in that module

A TypeError is thrown saying "TypeError: An error occurred while rendering BugReportForm 44: Cannot read property 'data' of undefined"

This seems to be caused by an assumption that a given dependency is always a module dependency, causing `mod` to become undefined when it isn't.<details>
<summary>Active Modules</summary>
betterCurses--v2.2.1;
bug-reporter--v1.2.1;
</details>

### PR DESCRIPTION
**Pull request by Ethck**
Closes #96 where module fails to load with non-module dependencies. This commit adds some safeguards to catch system and world dependencies.

### CODE REVIEW

File: Module/main.js [hunk 1]
```diff
@@ -199,12 +199,19 @@ class BugReportForm extends FormApplication {
...
     return this.module.data.dependencies?.map((dependency) => {
-      const mod = game.modules.get(dependency.name);
+      let plugin = game.modules.get(dependency.name);
+      if (plugin === undefined){
+        if (dependency.name === game.system.data.name) {
+          plugin = game.system;
+        } else if (dependency.name === game.world.data.name) {
+          plugin = game.world;
+        }
+      }
```
Comment (akrigline) [inline Module/main.js:213]: I believe there's a `type` field on dependency which could be used in a `switch` here:
```js
switch (dependency.type) {
  case "module":
// ...
  case "system":
// ...
  case "world":
// ...
}
```

**Review by akrigline — APPROVED** [review]
